name: Release

on:
  push:
    tags:
      - "v*"

env:
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10'

      - name: Restore NuGet packages
        run: dotnet restore Stratum.sln

      - name: Run tests
        run: dotnet test --configuration $env:CONFIGURATION --no-restore Stratum.Test/Stratum.Test.csproj

      - name: Publish Windows app
        run: dotnet publish --configuration $env:CONFIGURATION --no-restore -r win-x64 --self-contained -o publish Stratum.Windows/Stratum.Windows.csproj

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stratum-Windows
          path: publish/
